### ISSUE TITLE
Request for MEC Magrope Plus

### ISSUE THREAD

**Issue by Daniil1995** [zhpete/merge-strings-txt#5]
Hello! Your Magrope Plus is one of the best mods!!! Author, please, can you make magrope distance unlimited instead of 15 meters? Like scripted magropes in mod Mission Areas Freeroam, where, for example, magrope helps to overcome huge distances to the top of Anansi building.

**Comment by zhpete** [comment]
Sadly that's not feasible for technical reasons, sorry. By the way this isn't the right place to make mod requests, please do that on nexusmods
